spring:
  application:
    name: application-local
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  jpa:
    hibernate:
      ddl-auto: create
      #show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  datasource:
    url: jdbc:mariadb://localhost:3306/scentasy
    username: ${DB_USR}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    stack:
      auto: false

jwt:
  secret:
    key: ${JWT_KEY}
